### ISSUE TITLE
Will you keep updating on new methods?

### ISSUE THREAD

**Issue by YubinXie** [dynverse/dynbenchmark#29]
Thanks for the great work!
There are more single-cell trajectory inference methods published recently and surely in the future. Will you keep adding the new methods into your evaluation? Thanks!

**Comment by rcannood** [comment]
We indeed intend on releasing updates of the benchmark results. We did spend quite a bit of effort writing documentation on how to evaluate your own method using our packages ([](https://dynverse.org)), and also in order to make it easier to add to our pipeline.

**Comment by rcannood** [comment]
We indeed intend on releasing updates of the benchmark results. We did spend quite a bit of effort writing documentation on how to evaluate your own method using our packages (dynverse.org), which would also allow us to add it to our pipeline more easily.

**Comment by zouter** [comment]
Thank you, great question!

It is in the very least our intention to wrap more methods. We spend quite some time to make "wrapping" a method as straightforward as possible: https://dynverse.org/developers/creating-ti-method/ So we're also hoping that method developers create wrappers for their own methods, so that they're directly integrated within the dyno pipeline.

We also have some plans to update the benchmark to make it more "collaborative". But more info on that in a couple of months (if time allows :wink: )

**Comment by rcannood** [comment]
I guess we were writing concurrent answers, but it's good to see @zouter and I are still on the same page ;) 

@YubinXie Has this answered your question?

**Comment by YubinXie** [comment]
Thank you for your response. Yea, this answered my question.

Myself do not work on trajectory method, but I'd like to know the benchmarks in case I use them in the future... thanks again for your good works!
